package com.bridgeflow.api.audit;

public enum AuditAction {
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_ARCHIVED,
    REQUIREMENT_CREATED,
    REQUIREMENT_REVISED,
    REQUIREMENT_CONFIRMED,
    REQUIREMENT_ARCHIVED,
    GLOSSARY_TERM_CREATED,
    GLOSSARY_TERM_UPDATED,
    GLOSSARY_TERM_DELETED,
    DOCUMENT_UPLOADED,
    DOCUMENT_VERSION_ADDED,
    DOCUMENT_ARCHIVED,
    AI_EXTRACTION_REQUESTED,
    AI_EXTRACTION_COMPLETED,
    AI_EXTRACTION_FAILED,
    AI_ANALYSIS_REQUESTED,
    AI_ANALYSIS_COMPLETED,
    AI_ANALYSIS_FAILED,
    CLARIFICATION_ANSWERED,
    CLARIFICATION_REVIEWED,
    ACCEPTANCE_CRITERION_REVIEWED
}
