logging:
  structured:
    format:
      console: logstash

management:
  endpoint:
    health:
      show-details: never

server:
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
